M48
; DRILL file {KiCad (6.0.7)} date Tue Sep  6 00:26:26 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-06T00:26:26+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X3.3449Y-5.2819
X3.361Y-2.7331
X7.1201Y-5.2697
X7.1425Y-2.6961
T0
M30
